default:
  # The default setting for the configuration file is set to use pre-existing 
  # centers and collated datasets. 
  google_email: "" # enter google email
  calculate_centers: FALSE # the center calculation will not run, and previously-
  # collated centers will be used
  centers_version: "2025-02-12" # yyyy-mm-dd of version, must be a date listed in the 
  # suffix of the files documented wihtin the 
  # a_Calculate_Centers/out/lakeSR_poi_with_flags_drive_ids_xxDATExx.csv file
  run_GEE: FALSE # boolean, the GEE acquisition will not be run, and previously-collated
  # data will be used
  collated_version: "2025-02-12" # yyyy-mm-dd of version, must be a date listed in the 
  # suffix of the .csv files stored in c_collate_Landsat_data/out/
  parent_Drive_folder: "~/lakeSR_Landsat_C2/" # optional. character string, parent folder 
  # location to store files on Google Drive. Can also be "" if no parent folder desired.
  # Only used if calculate_centers, run_gee, and/or update_and_share set to TRUE.
  update_and_share: FALSE # boolean, indication of whether the qa steps should be 
  # re-run and updated to Drive. If TRUE, qa steps will be run locally and .csv
  # and feather files will be created and sent to drive. If FALSE, the previously-
  # created/shared files with the `qa_version` below will be used in the pipeline.
  qa_version: "2025-06-04" # yyyy-mm-dd of filtered/qa'd files to filter by if 
  # update_and_share is FALSE, otherwise, the NEW version date you are creating.
  update_bookdown: FALSE # boolean, if the bookdown will be re-rendered
  siteSR_repo_directory: "../AquaMatch_siteSR_WQP/" # relative directory path where
  # the siteSR directory is located. only needed if update_bookdown is set to TRUE

admin_update:
  # this setting will run the entire pipeline and will create publicly available 
  # files using the google_email account listed
  google_email: "therossyndicate@gmail.com" 
  calculate_centers: TRUE
  centers_version: "2025-02-12" # update upon initial run, or if changes in -a-
  # group. if unchanged, updated files will be overwritten.
  run_GEE: TRUE 
  parent_Drive_folder: "~/lakeSR_Landsat_C2/"
  update_and_share: TRUE 
  qa_version: "2025-06-04"
  update_bookdown: TRUE 
  siteSR_repo_directory: "../AquaMatch_siteSR_WQP/" 
