default:
  # The default setting for the configuration file is set to use pre-existing 
  # centers and collated datasets. 
  siteSR_repo_directory: "../AquaMatch_siteSR_WQP/" # relative directory path where
  # the siteSR directory is located
  google_email: "therossyndicate@gmail.com" # enter google email
  calculate_centers: FALSE # the center calculation will not run, and previously-
  # collated centers will be used
  centers_version: "2025-02-12" # yyyy-mm-dd of version, must be a date listed in the 
  # suffix of the files documented wihtin the 
  # a_Calculate_Centers/out/combined_poi_drive_ids.csv file
  run_GEE: FALSE # the GEE acquisition will not be run, and previously-collated
  # data will be used
  collated_version: "2025-02-12" # yyyy-mm-dd of version, must be a date listed in the 
  # suffix of the .csv files stored in c_collate_Landsat_data/out/
  update_sorted_in_Drive: TRUE # boolean, if data, sorted by HUC4 should be saved to 
  # drive
  parent_Drive_folder: "~/lakeSR_Landsat_C2/" # character string, parent folder 
  # location to store the sorted files. Can also be "" if no parent folder desired.
  update_bookdown: TRUE # boolean, if the bookdown will be re-rendered

admin_update:
  # this setting creates publicly available files using the ROSS account
  siteSR_repo_directory: "../AquaMatch_siteSR_WQP/" # relative directory path where
  # the siteSR directory is located
  google_email: "therossyndicate@gmail.com" # enter google email
  calculate_centers: TRUE # the center calculation will run locally
  centers_version: "2025-02-12"
  run_GEE: TRUE # the GEE acquisition will be run locally
  # collated version date will populate from the `run_date` listed in the config
  # file for the GEE run: `b_pull_Landsat_SRST_poi/config_files/config_poi.yml`
  update_sorted_in_Drive: TRUE # boolean, if data, sorted by HUC4 should be saved to 
  # drive
  parent_Drive_folder: "~/lakeSR_Landsat_C2/" # character string, parent folder 
  # location to store the sorted files. Can also be "" if no parent folder desired.
  update_bookdown: TRUE # boolean, if the bookdown will be re-rendered and/or knit