graph LR
  subgraph legend
    direction LR
    x7420bd9270f8d27d([""Up to date""]):::uptodate --- x0a52b03877696646([""Outdated""]):::outdated
    x0a52b03877696646([""Outdated""]):::outdated --- xbf4603d6c2c2ad6b([""Stem""]):::none
    xbf4603d6c2c2ad6b([""Stem""]):::none --- x70a5fa6bea6f298d[""Pattern""]:::none
    x70a5fa6bea6f298d[""Pattern""]:::none --- x5bffbffeae195fc9{{""Object""}}:::none
    x5bffbffeae195fc9{{""Object""}}:::none --- xf0bce276fe2b9d3e>""Function""]:::none
  end
  subgraph Graph
    direction LR
    x0e80a0b3aa63f1e9(["collated_poi_points"]):::uptodate --> x374d007457c599ab(["NHDHR_poi_points_file"]):::uptodate
    x374d007457c599ab(["NHDHR_poi_points_file"]):::uptodate --> x7c30997b2dacad3c(["NHDHR_poi_points"]):::uptodate
    x7c30997b2dacad3c(["NHDHR_poi_points"]):::uptodate --> xa686a3a91e8f4a73(["NHDHR_poi_points_noAK"]):::uptodate
    x2c0456c7217116f1>"calculate_centers_HUC4"]:::uptodate --> xf47f79c35e045110["all_poi_points"]:::uptodate
    xd288ec88382fd531(["HUC4_list"]):::uptodate --> xf47f79c35e045110["all_poi_points"]:::uptodate
    x4b49df1faec88974(["US_states_territories"]):::uptodate --> x563e63e40cc2048a["HUC4_dataframe"]:::uptodate
    x563e63e40cc2048a["HUC4_dataframe"]:::uptodate --> xd288ec88382fd531(["HUC4_list"]):::uptodate
    x5782ee7b5f1f3a55(["empty_hucs_file_file"]):::uptodate --> x36cc737b097c7596(["empty_hucs_file"]):::uptodate
    x8523d1b0728d44d8(["combined_poi_file"]):::uptodate --> x666819ed6cb97b5b(["combined_poi_points_file"]):::uptodate
    xf47f79c35e045110["all_poi_points"]:::uptodate --> x0e80a0b3aa63f1e9(["collated_poi_points"]):::uptodate
    x1e45a41c07a3238d(["AK_poi_points_file"]):::uptodate --> x94ec576089d222c0(["AK_poi_points"]):::uptodate
    x8990c636ae27413a(["make_AK_poi_points"]):::uptodate --> x1e45a41c07a3238d(["AK_poi_points_file"]):::uptodate
    xc512100d57791085>"calculate_AK_poi"]:::uptodate --> x8990c636ae27413a(["make_AK_poi_points"]):::uptodate
    x94ec576089d222c0(["AK_poi_points"]):::uptodate --> x8523d1b0728d44d8(["combined_poi_file"]):::uptodate
    xf20d47e4fd13ba22>"collate_NHDHR_AK"]:::uptodate --> x8523d1b0728d44d8(["combined_poi_file"]):::uptodate
    xa686a3a91e8f4a73(["NHDHR_poi_points_noAK"]):::uptodate --> x8523d1b0728d44d8(["combined_poi_file"]):::uptodate
    xf47f79c35e045110["all_poi_points"]:::uptodate --> x5782ee7b5f1f3a55(["empty_hucs_file_file"]):::uptodate
    x666819ed6cb97b5b(["combined_poi_points_file"]):::uptodate --> xb7c2e4e3c478a530(["combined_poi_points"]):::uptodate
    x992c5ff226ae9b16(["make_empty_huc_file"]):::uptodate --> x992c5ff226ae9b16(["make_empty_huc_file"]):::uptodate
    x63a44b4091e88968{{"a_Calculate_Centers_list"}}:::outdated --> x63a44b4091e88968{{"a_Calculate_Centers_list"}}:::outdated
  end
  classDef uptodate stroke:#000000,color:#ffffff,fill:#354823;
  classDef outdated stroke:#000000,color:#000000,fill:#78B7C5;
  classDef none stroke:#000000,color:#000000,fill:#94a4ac;
  linkStyle 0 stroke-width:0px;
  linkStyle 1 stroke-width:0px;
  linkStyle 2 stroke-width:0px;
  linkStyle 3 stroke-width:0px;
  linkStyle 4 stroke-width:0px;
  linkStyle 23 stroke-width:0px;
  linkStyle 24 stroke-width:0px;
