# yaml file to configure the Landsat C2 SR & ST parameters for this repository's 
# {targets} workflow

local_settings:
- unique_id: "rowid" # this is the column that stores the unique identifier for each site, should not contain any special characters
- latitude: "poi_Latitude" # this is the column that stores the latitude of the site, must be in decimal degrees
- longitude: "poi_Longitude" # this is the column that stores the longitude of the site, must be in decimal degrees
- location_crs: "EPSG:4326" # this is the coordinate reference system of the location data, must be in EPSG format (e.g. EPSG:4326)

google_settings:
- proj: "LSC2_poi" # this is a short name for file naming conventions. All output files will include this prefix.
- proj_folder: "ls_c2_srst_poi" # this is the folder name where the GEE data will be save to Google Drive. If it doesn't exist, it will be created.
- ee_proj: "ee-ls-c2-srst" # this is the ee project name you are running your pulls from

temporal_settings: 
- start_date: "1983-01-01" # earliest data of satellite data to be acquired; earliest data available is 1983-01-01
- end_date: "2023-07-01" # latest data of satellite data to be acquired; if 'today' is used, the date will be set to the current date

spatial_settings: 
- extent: "site" # options: "site", "polygon", "polycenter", "site+poly", "site+polygon+polycenter", "polygon+polycenter" - at this time lake and lake center can only be calculated for lakes in the US
- site_buffer: 120 # buffer distance in meters around the site or poly center

gee_settings:
- cloud_filter: "True" # True or False - if True, scenes will be filtered by scene-level cloudy value provided in the metadata
- cloud_thresh: 90 # scenes with a cloud value greater than this threshold will be filtered out
- water_detection: "DSWE" # "DSWE" is currently the only option for water detection. Future iterations may include Peckel water instance or another method.
- DSWE_setting: "1" # 1, 3, or 1+3. DSWE 1 only summarizes high confidence water pixels; DSWE 3 summarizes vegetated pixels. 

