---
editor_options: 
  markdown: 
    wrap: 80
bibliography: references.bib
---

# Background

Currently, AquaSat v2 remote sensing products include the historical Landsat
Collection 2 record from 1984 until late 2024, comprised of data from the
following missions:

-   Landsat 4 Thematic Mapper (TM)
-   Landsat 5 TM
-   Landsat 7 Enhanced Thematic Mapper Plus (ETM+)
-   Landsat 8 Operational Land Imager/Thermal Infrared Sensor (OLI/TIRS)
-   Landsat 9 OLI/TIRS

There will be additional satellite data incorporated into AquaSat v2 in the
future.

## lakeSR Code Architecture

[lakeSR code](https://github.com/AquaSat/AquaMatch_lakeSR) is broken down into
groups of targets that perform specific tasks, listed below with a brief summary
about what task(s) each group completes. This particular workflow incorporates
both R and Python programming languages to complete these tasks.

### {targets} groups

**a_Calculate_Centers**:

This {targets} list calculates "Pole of Inaccessibility" (POI)
[@garcia-castellanos2007] for all non-intermittent lakes, ponds, and reservoirs
greater than 1 hectare in surface area and intermittent lakes, ponds, and
reservoirs greater than 4 hectares using the NHDPlusV2 polygons using the
{nhdplusTools} package [@blodgett2023], NHD Best Resolution files for non-CONUS
waterbodies, and the `poi()` function in the {polylabelr} package
[@larsson2020].

See Section \@ref(locs-data-acq) for additional background and detailed
methodology.

**b_pull_Landsat_SRST_poi**:

This {targets} group uses the configuration file
`b_pull_Landsat_SRST_poi/config_files/config_poi.yml` and the "Pole of
Inaccessibility" points created in the `a_Calculate_Centers` group to pull
Landsat Collection 2 Surface Reflectance and Surface Temperature using the
Google Earth Engine (GEE) API. In this group, we use the most conservative LS4-7
pixel filters, as we are applying these settings across such a large continuum
of time and space. This group ends with a branched target that sends tasks to
Google Earth engine by mapping over WRS2 path rows that intersect with the
points created in the `a_Calculate_Centers` group. **Note**: this group of
targets takes a very, very long time, running 2 minutes - 1 hour per path-row
branch in `b_eeRun_poi`. There are just under 800 path rows executed in this
target. Anecdotally speaking, processing time is often defined by the number of
queued tasks globally, so weekends and nights are often periods of quicker
processing than weekday during business hours.

See Section \@ref(software-settings) for details on software used in this
workflow, Section \@ref(LS-C2-SRST) for additional background on Landsat data,
and Section \@ref(LS-SRST-pull) for detailed methodology of the Landsat pull.

**c_collate_filter_lakeSR:**

**d_calculate_apply_handoff:**

## siteSR_WQP Code Architecture

[siteSR_WQP code](https://github.com/AquaSat/AquaMatch_siteSR_WQP) is built upon
the output of
[AquaMatch_hamronize_WQP](https://github.com/AquaSat/AquaMatch_harmonize_WQP)
and [lakeSR](https://github.com/AquaSat/AquaMatch_lakeSR).
AquaMatch_harmonize_WQP provides harmonized *in situ* data from the Water
Quality Portal for pairing with remote sensing data acquired at the sites of *in
situ* data. This workflow picks up where AquaMatch_harmonize_WQP ends, with the
output of harmonized, tiered, and aggregated datasets per water quality
parameter. lakeSR provides calculated Landsat intermission handoff coefficients
for interoperability between sensors. In order to run the siteSR_WQP workflow,
you must have a cloned version of AquaMatch_harmonize_WQP and AquaMatch_lakeSR
codebase on your local computer. Section \@ref(setup-description) covers details
about this requirement.

### Configuration Files {#setup-description}

**config.yml:**

siteSR_WQP relies on this configuration file to run specific profiles that
determine what operations are being run. The file contains three configuration
profiles: "default", "admin_update", and "use_stable".

-   "default" runs the pipeline **without** using any stable versions of
    datasets made with AquaMatch_harmonize_WQP. This requires that the
    AquaMatch_harmonize_WQP pipeline has been run locally.

-   "use_stable" uses publicly-posted stable versions of datasets from
    AquaMatch_harmonize_WQP and is intended for those who wish to modify choices
    made in siteSR_WQP or for those who wish to have the complete pipeline on
    their local device

-   "admin_update" is intended for use by ROSSyndicate members when updating
    siteSR datasets and create publicly-stable versions of the siteSR_WQP to be
    stored in the AquaMatch_siteSR_WQP repository

All configurations will be reliant on the stable version of handoff coefficients
calculated in AquaMatch_lakeSR, as re-running that workflow takes multiple days.
Advanced users are welcome to adapt the pipeline to incorporate other handoff
methods. **The Landsat Surface Reflectance product should not be used without
applying a handoff coefficient if you are using data from multiple Landsat
missions.**

Proper configuration of `harmonize_repo_directory` and `lakeSR_repo_directory`
is imperative as the siteSR_WQP workflow references files inside
AquaMatch_harmonize_WQP and AquaMatch_lakeSR file structures. If this is
incorrectly set up, users will receive a message to communicate this. All
repositories stored on the AquaSat v2 GitHub will contain files that link to
versions of the data that the AquaSat v2 team has harmonized so that a local run
is not necessitated. Any run of the "default" configuration will require that
the harmonize pipeline has been run locally.

**gee_config.yml**:

This configuration file defines parameters of the GEE pull. This configuration
can be customized. To create a different configuration of the GEE pull, fill out
the yaml file at the file path `gee_config.yml`. If you change the name of this
file, you will need to update the file name at line 13 of the `5_siteSR_stack.R`
file.

### {targets} Groups

**\_targets.R:**

This initial group of targets checks the configuration settings in `config.yml`,
checks for the harmonization and lakeSR pipelines, and checks for Google Drive
folder architecture. This group also acquires target objects from the
harmonization and lakeSR pipelines.

**4_compile_sites:**

This {targets} group collates the sites from the harmonization pipeline,
creating a list of locations to acquire remote sensing data. All locations are
associated with a HUC8 if one is not listed in the metadata for the site from
the WQP, then the unique HUC4s are used to associate points with waterbodies and
flowlines of the NHDPlusV2 (CONUS) or NHD Best Resolution (non-CONUS HUCs)
files.

**5_siteSR_stack:**

The resulting list of *in situ* locations are used to acquire Landsat Collection
2 SRST data in this {targets} group. Sites are assessed for visibility using the
JRC Global Surface Water [@pekel2016] which is based on the historical Landsat
record. Sites determined to be visible are used to define the GEE Landsat pull.

**6_siteSR_collate_filter_handoff:**

**7_siteSR_matchup:**
