---
editor_options:
  markdown:
    wrap: 80
bibliography: references.bib
---

# Satellite Data Acquisition Software and Settings {#software-settings}

Currently, all satellite data in AquaMatch are obtained using the Python API for
Google Earth Engine [GEE, @gorelick2023]. While the orchestration of data
acquisition is performed by the {targets} workflow, all code directly related to
GEE data acquisition is written in Python. If you are running the 'default'
configuration for lakeSR or siteSR the following directions are not applicable.

## R Environment and Package Information

We recommend using the most recent release of R, R Studio, {targets} and all R
packages used within the workflow. The most recent run of lakeSR and siteSR was
completed using R version 4.5.0 [@rcoreteam2025] in R Studio 2025.05.0
[@positteam2023] . The table below lists the packages used across the lakeSR and
siteSR workflow, versions used, and the associated citation.

| R Package    | version  | citation                   |
|--------------|:--------:|----------------------------|
| arrow        | 20.0.0.2 | @richardson2025            |
| bookdown     |   0.43   | @xie2016, @xie2025         |
| config       |  0.3.2   | @allaire2023               |
| cowplot      |  1.1.3   | @wilke2024                 |
| crew         |  1.1.2   | @landau2025                |
| data.table   |  1.17.4  | @barrett2025               |
| deming       |  1.4-1   | @therneau2024              |
| ggrepel      |  0.9.6   | @slowikowski2024           |
| ggthemes     |  5.1.0   | @arnold2024                |
| googledrive  |  2.1.1   | @mcgowan2023               |
| kableExtra   |  1.4.0   | @zhu2024                   |
| nhdplusTools |  0.6.2   | @blodgett2023              |
| polylabelr   |  0.3.0   | @larsson2024               |
| reticulate   |  1.42.0  | @ushey2025                 |
| rmapshaper   |  0.5.0   | @teucher2023               |
| sf           |  1.0-21  | @pebesma2018, @pebesma2023 |
| tarchetypes  |  0.13.1  | @landau2021b               |
| targets      |  1.11.3  | @landau2021                |
| tidyverse    |  2.0.0   | @wickham2019               |
| tigris       |  2.2.1   | @walker2025                |
| viridis      |  0.6.5   | @garnier2024               |
| xml2         |  1.3.8   | @wickham2025               |
| yaml         |  2.3.10  | @garbett2024               |

## {reticulate} Conda Environment

RStudio [@positteam2023] is an IDE that, alongside the {reticulate} package
[@ushey2025], facilitates integration of R and Python code within the same
environment. In AquaMatch, we use [a single R
script](https://github.com/AquaSat/lakeSR/blob/main/python/pySetup.R) to set up
a {reticulate} Conda environment that is invoked at the beginning of a {targets}
run to be sure that our Python code runs consistently.

| Software/Python Module | version | citation |
|---------------------------|:-------------------------:|---------------------------|
| Python | 3.10.13 | Python Software Foundation, [www.python.org](www.python.org) |
| earthengine-api | 1.4.0 | @gorelick2023 |
| pandas | 2.0.3 | @thepandasdevelopmentteam2023 |
| pyreadr | 0.5.2 | @fajardo2023 |
| PyYAML | 6.0.2 | The PyYAML Project, <https://github.com/yaml/pyyaml> |
| numpy | 1.24.4 | @harris2020 |

: Python and python module

The script `run_targets.Rmd` includes the steps to create this environment and
authenticate your GEE user. These steps should be run prior to running the
pipeline to assure a smooth run of the workflow.

## Google Earth Engine Setup

If running the 'admin_update' configuration for either lakeSR or siteSR, you
will need to have a GEE account, the gcloud CLI installed and configured, create
an Earth Engine Project, have successful authenticated your account, and you
will need to alter the configuration file. All of these tasks are described in
the section below.

### Create a GEE account {#create-account}

Creation of a GEE account is free. Click 'Get Started' at the far right side of
the [earthengine.google.com](https://earthengine.google.com) webpage to create
an account:

[![Header of earthengine.google.com with link to create a GEE account
highlighted in the red box to the
right.](images/EE_header.png)](https://earthengine.google.com)

### gcloud CLI {#gcloud}

This workflow requires the installation and initiation of [gcloud
CLI](https://cloud.google.com/sdk/gcloud), a command-line tool set for accessing
Google Cloud Resources. All settings for AquaSat v2 are default `gcloud`
configurations using a single GEE project. The link above documents how to set
up gcloud.

### GEE project setting {#proj-setting}

AquaMatch is run in a specific GEE project associated with our authenticated
Google account. If you wish to re-run this code as written, you will not have
proper access because the code refers to our specific GEE project. You will need
to update the config yaml (in lakeSR:
`b_pull_Landsat_SRST_poi/config_files/config_poi.yml`, in siteSR:
`gee_config.yml`) with your Google credentials and GEE project in order to run
the pipeline locally. If you are new to GEE, go to
[code.earthengine.google.com](https://code.earthengine.google.com) and enter the
project name listed in the top right hand corner of your screen:

![Header of code.earthengine.google.com with current Earth Engine project
highlighted in the red box to the right.](images/code_ee_proj.png)

Alternatively, you can create a GEE project for this task in the dropdown menu
accessed by clicking on the icon to the right of the highlighted box in the
figure above. This workflow will not run without specifying an Earth Engine
Project that is managed by the Google Account you authenticate this run with.

### GEE Authentication {#auth}

Once `gcloud` is installed and initialized, the configuration file is properly
set up, and the Conda environment is set up, you can authenticate your GEE
instance. For this workflow, this is completed in the `run_targets.Rmd` script
at the root directory. This script provides explicit directions to complete this
task before running the pipeline.
