---
editor_options:
  markdown:
    wrap: 80
bibliography: references.bib
params:
  cfg: NA
  LS_files: NA
---

```{r chunk-opts-6, echo=FALSE}
knitr::opts_chunk$set(echo = FALSE, 
                      message = FALSE, 
                      warning = FALSE, 
                      error = FALSE)

library(tidyverse)
library(googledrive)
library(arrow)

# for whatever reason, knitr::include_graphics is being kind of weird
# so here, we'll copy the files from d_qa_filter_calc_handoff/out and put them in images here
# Define source and destination directories
source_dir <- "../d_qa_filter_calc_handoff/out/"
dest_dir <- "images/"

# Get list of files to copy
files_to_copy <- list.files(source_dir, full.names = TRUE)

# Copy files
file.copy(from = files_to_copy, to = dest_dir, overwrite = TRUE)

```

# Basic Quality Assurance and Calculating Intermission Handoffs {#handoff}

Up until this point in the workflow, no data filtering has occurred other than
the masking procedures that eliminate obviously contaminated pixel-level data
due to sensor malfunction, clouds, haze, and glint as described in Section
\@ref(masking-functions). We also implement further QA filters for the remote
sensing stacks to assure high-quality data. These post-hoc filters are described
in \@ref(post-hoc-filters).

Additionally, it is necessary to standardize band values between Landsat
missions in order to create a robust timeseries. @maciel2023 notes the issues in
using the Landsat Surface Reflectance product as a timeseries without careful
handling of data between missions. This standardization process attempts to
address changes in sensor spectral response and atmospheric correction
procedures. For the purposes of AquaSat v2, we call this standardization process
"intermission handoffs". We implement two versions of intermission handoffs: the
method described in @roy2016 ("Roy method") and an adapted version of that
described in @gardner2021 ("Gardner method") (described in section
\@ref(define-handoff)).

## Raw lakeSR stack collation {#raw-lakesr}

The data exported from the GEE tasks described in Section \@ref(LS-SRST-pull)
were collated into large compressed .feather files per DSWE type (DSWE1 and
DSWE1a), per Landsat mission, and per path prefix. The path prefix subset is
designed to reduce data corruption due to file size in the upload/download
process to Google Drive, where the collated files are stored for posterity and
to add functionality to this workflow. The Google Drive ids can be found at the
folder path `c_collate_Landsat_data/out/` and can be accessed without special
permissions by downstream users. Many of these files are quite large (on the
order of many GBs) and are very difficult to handle outside of a programming or
database environment. We provide these files for advanced users who wish to make
changes to the QAQC or intermission handoff procedures. At the time of running
the pipeline, we assigned a max vector size ('R_MAX_VSIZE') of 32 GB using the
.Renviron document in this repository and it was run on a machine with 64 GB of
memory. If your system has less than 32 GB of memory, this portion of the
workflow may not successfully run.

## Post-hoc filters {#post-hoc-filters}

We acknowledge that even with the best masking procedures, our workflow may
still result in erroneous or misleading SR values. To address this we implement
post-hoc filters that are applied to the stack to reduce uncertainty in the
remote sensing data as much as possible.

-   total count of pixels (`pCount_dswe1` or `pCount_dswe1a`) contributing to
    summary values must be ≥ 8. This is a slight change from AquaSat v1 which
    required 10 pixels. Due to the more rigorous masking procedures (thant ASv1)
    we believe allows for a slightly more conservative QA filter via the
    reduction of required pixels for inclusion in the lakeSR dataset.

-   if the median temperature is below freezing (`med_SurfaceTemp` \< 273.15 °
    K), the row is dropped. This is our best attempt at removing data during any
    freezing period and also is an attempt at detecting clouds which can impact
    the thermal estimates. In particular, cirrus clouds can go unnoticed in
    cloud detection algorithms used that inform our masking procedures.

-   either NIR surface reflectance or SWIR1 and SWIR2 surface reflectance must
    be \< 0.1, this is to remove any extracted samples where sun glint has
    likely affected the data that was not masked in the RGB bands. In aquatic
    environments, NIR, SWIR1, and SWIR2 surface reflectance values should be
    very low and these bands can be used for detecting sun glint affected areas
    [e.g. @mondejar2019, @vanhellemont2019]. Since NIR bands can be elevated in
    high-sediment waters [e.g., @doxaran2002] and SWIR can be elevated in high
    chlorophyll environments [e.g, @hu2009], and we did not wish to bias our
    dataset and remove data of this nature, we embraced this conditional
    approach.

While there are numerous other diagnostic tests we could apply to filter the RS
data, these are the QA filters that we deem to be the most foundational and
unifying for reliable RS data across the US and Territories.

### Landsat 4 QA Summary

![Summary of dropped rows for Landsat 4's DSWE1 (confident water) RS
summaries.](images/LT04_dswe1_drop_summary.png)

![Summary of dropped rows for Landsat 4's DSWE1a (confident water with positive
algal mask) RS summaries.](images/LT04_DSWE1a_drop_summary.png)

### Landsat 5 QA Summary

![Summary of dropped rows for Landsat 5's DSWE1 (confident water) RS
summaries.](images/LT05_DSWE1_drop_summary.png)

![Summary of dropped rows for Landsat 5's DSWE1a (confident water and positive
algal mask) RS summaries.](images/LT05_DSWE1a_drop_summary.png)

### Landsat 7 QA Summary

![Summary of dropped rows for Landsat 7's DSWE1 (confident water) RS
summaries.](images/LE07_DSWE1_drop_summary.png)

![Summary of dropped rows for Landsat 7's DSWE1a (confident water and positive
algal mask) RS summaries.](images/LE07_DSWE1a_drop_summary.png)

### Landsat 8 QA Summary

![Summary of dropped rows for Landsat 8's DSWE1 (confident water) RS
summaries.](images/LC08_DSWE1_drop_summary.png)

![Summary of dropped rows for Landsat 8's DSWE1a (confident water and positive
algal mask) RS summaries.](images/LC08_DSWE1a_drop_summary.png)

### Landsat 9 QA Summary

![Summary of dropped rows for Landsat 9's DSWE1 (confident water) RS
summaries.](images/LC09_DSWE1_drop_summary.png)

![Summary of dropped rows for Landsat 9's DSWE1a (confident water and positive
algal mask) RS summaries.](images/LC09_DSWE1a_drop_summary.png)

## Calculating intermission handoffs {#define-handoff}

In AquaSat v2, we standardize values relative to Landsat 7 (`corr7`) and Landsat
8 (`corr8`). The Landsat 7 intermission handoffs can be applied the entire
Landsat 4-9 because it overlapped with early Landsat (4/5) and modern Landsat
(8/9). For the `corr7` standardization, we treat Landsat 4 and 5 as
interchangable, given that the satellites contained the same payload and
radiometric resolution. We also treat Landsat 8 and 9 as interchangable despite
the slight differences in radiometric resolution. Landsat 8 handoffs (`corr8`)
can only be applied to Landsat 7 and 9 due to mission overlap, so the
standardized data timeseries is shorter; however, it may be more robust for
analyses focused in the recent past that rely on Landsat 9 data given the
previously-mentioned caveats for application of `corr7` to that mission.

### Roy method

The Roy method for calculating intermission handoffs uses paired images at
specific sites, where the reflectance data are obtained are from two missions
(e.g. Landsat 7 and Landsat 8) separated by one day at a specific location
within the overlapping paths in the WRS2 path-row framework (see figure
@ref(path-overlap-roy)).

![An example of two overlapping WRS2 paths (grey area) separated by one day. Any
location with data for both images would be considered a paired data point to
define the Roy method intermission handoffs.](images/path_overlap_roy.png)

While @roy2016 implement this method on a pixel-by-pixel basis, we implement
using the median band value per site. This is used in place of the explicit
filters of saturated pixels, cloudy/snowy pixels, and pixels with value changes
greater than the changes in atmospheric correction as described in the text, as
we have implemented masks and QA filters to eliminate these sources of error.
Handoff coefficients are defined by the ordinary least squares regression line
of the Landsat 7 against the Landsat 8 data.

### Garnder method

Gardner method intermission handoffs are defined by the data obtained in the
overlapping period of time between two adjacent-in-time missions (details
provided in Figure \@ref()). These data are summarized to each mission's
1st-99th percentile value per band, and the handoff coefficients between
missions are defined by the second-order polynomial relationship between them.
Because we use a second-order polynomial, all values outside of the 1st and 99th
percentile values used to define the intermission handoff are flagged and should
be used with extreme caution. All `corr7` and `corr8` relationships and their
derived coefficients are provided in the sections below.

| Early mission | Late mission |   |   | Proportion of years required | N scenes of early mission | N scenes of later mission |
|----------|----------|--------|---------|----------------|----------------|----------------|
| LS5 | LS7 |  |  | 0.75 | `r format(d_LS5_forLS57corr_quantiles$n_scenes[1], big.mark = ",")` | `r format(d_LS7_forLS57corr_quantiles$n_scenes[1], big.mark = ",")` |
| LS7 | LS8 |  |  | 0.75 | `r format(d_LS7_forLS78corr_quantiles$n_scenes[1], big.mark = ",")` | `r format(d_LS8_forLS78corr_quantiles$n_scenes[1], big.mark = ",")` |

### `corr7` handoff coefficients

[[pull figs from functions here]]

[[insert table of calcs, \# of points, etc]]

### `corr8` handoff coefficients

[[pull figs from functions here]]

[[insert table of calcs, \# of points, etc]]
