---
title: "08-AquaMatch_Remote_Sensing_Limitations"
editor_options: 
  markdown: 
    wrap: 80
bibliography: references.bib
---

# Limitations of the AquaMatch Remote Sensing Dataset

Given the size and nature of this dataset, we took as many precautions as possible
to reduce error, contamination, and mis-attribution within our dataset. With that, there are a 
number of limitations that have been covered throughout this documentation that we
would like to note for end users. 

1) Within AquaMatch, we assume static water level for site-level flag attribution
  - especially in the arid west or in systems with water level fluctuations, 
  additional care should be taken when interpreting the flags provided in the
  site file (``)
  
2) The extraction of Landsat Surface Reflectance values may contain data from 
additional nearby water sources that are within the site buffers.
  - e.g. point near dam could obtain both surface water in waterbody as well
  as surface water of river
  - use the site file and NHD-related flags to determine if this is a consideration
  for the data you are using (see section XXXXX)
  
3) Surface Temperature is processed alongside SR, which may result in mixed pixel
values being incorporated within the summary statistics provided in AquaMatch (See section XXXXX)
  
3) some qualities of contaminated sr pixels can go unnoticed and unfiltered within
this dataset.
  - if there are sr values which seem odd, consider looking at the scene the
  data originated from to assess if the data are strange due to natural causes
  or because of unknown/unrecognized artifacts from atmospheric correction process
  - while we allow for slightly negative SR values to account for some atmospheric
  overcorrections over dark waterbodies, this assumes that there is a systematic
  overcorrection, which may not always be appropriate. Users should consider further
  filtering of the data if this type of allowance does not align with their analysis.
  - most of the bit flags we use to identify contaminated pixels are defined by
  alogorithms, which can make mistakes including omission of contaminated labels
  - Landsat 4-7 use interpreted opacity filters, which are dervied from other 
  remote sensing data and may over- or under-mask the area of interest. Cirrus
  and smoke contamination can still be present
  - Landsat 8/9 use an aerosol mask, which can sometimes miss cirrus and smoke 
  contamination
  