---
title: 'AquaMatch: Lake Surface Reflectance (lakeSR) and Site Surface Reflectance (siteSR)'
subtitle: 'Compiled Satellite Surface Reflectance and Surface Temperature for Waterbodies in the United States and US territories'
author: ROSSyndicate
date: "`r Sys.Date()`"
documentclass: book
site: bookdown::bookdown_site
bibliography: [../bookdown/references.bib]
biblio-style: apalike
link-citations: no
description: "Acquisition and compilation of satellite surface reflectance data for all lakes in the United States and US territories."
params:
  poi: NA
  locs_run_date: NA
  sites: NA
  visible_sites: NA
  LS5_for57: NA
  LS7_for57: NA
  LS7_for78: NA
  LS8_for78: NA
  LS57_match: NA
  LS78_match: NA
  coefficients: NA
---

# Introduction

This {bookdown} [@xie2016] document explains the methodology we use in the acquisition and compilation of satellite surface reflectance and surface temperature data for the AquaMatch data suite. AquaMatch is the data product coming from the revision of the original AquaSat dataset [@ross2019], sometimes referred to as AquaSat v2. Specifically, this document describes remotely-sensed data for all lakes greater than 1 hectare from the National Hydrography Dataset (NHD) in the United States and US territories. These data comprise "lakeSR" (lake surface reflectance). We also describe the remotely-sensed data associated with Water Quality Portal (WQP) monitoring locations and National Water Information System ("NWIS") sensor locations. These data comprise "siteSR" (site surface reflectance). Generally speaking, siteSR refers to remote sensing data acquired at locations with *in situ* data (from the WQP and NWIS) and lakeSR refers to remote sensing data acquired at centrally-located points of waterbodies (defined by the NHD).

The AquaSat v2 effort via AquaMatch represents modular code and data infrastructure for:

1.  harmonizing *in situ* data from the Water Quality Portal and providing an interoperability tiering structure to allow for easier downstream filtering (e.g. AquaMatch_harmonize_WQP)

2.  acquiring remote sensing data of inland waterbodies and rivers (lakeSR, siteSR, and riverSR (river surface reflectance))

3.  pairing *in situ* data and remote sensing data for parameter-specific algorithm development (e.g., data from the Water Quality Portal and the Landsat Collection 2 data product: AquaMatch_WQP_LandsatC2)

The goal of these data products is to facilitate assessment and monitoring of waterbodies within the United States and territories using both *in situ* and remote sensing data.

AquaMatch builds upon AquaSat [@ross2019] (referred to here as "AquaSat v1") and LimnoSat-US [@topp]. AquaSat v1 focused on pairing remote sensing data with *in situ* observations and measurements while LimnoSat-US acquired remote sensing for all waterbodies greater than 10 hectares across the Continental United States (CONUS) regardless of whether *in situ* measurements were available for that waterbody. In AquaMatch, we bring these products together. For instance, lakeSR can define Landsat intermission handoffs to enable use of Landsat as a timeseries product, siteSR products can be used to create parameter-specific algorithms, and those algorithms can be applied to a lakeSR "stack" to create a timeseries of water quality for waterbodies in the US and territories.

AquaMatch code is built on the {targets} workflow management system for R [@landau2021]. The {targets} architecture is based on lists of functions performed in a specific order, each function called a *target*. These targets are grouped together into processing groups. The primary benefit of {targets} workflows is that code is only run if a target, a target's code, or a target's dependencies have changed (or become "outdated" in {targets} speak).

Full documentation of the WQP download and quality assurance (QA) process from the upstream AquaMatch download and harmonize pipelines [is located here](https://aquasat.github.io/AquaMatch_documentation/).

## Repository Links for the AquaMatch Data Suite

[AquaMatch_download_WQP](https://github.com/AquaSat/AquaMatch_download_WQP): This repository contains code that downloads parameters from the WQP using the {dataRetrieval} package.

[AquaMatch_harmonize_WQP](https://github.com/AquaSat/AquaMatch_harmonize_WQP): This repository contains code that applies QA steps to the heterogenous dataset resulting from the WQP download. The pipleline applies tiering, flagging, and quality control across WQP parameter groups.

[AquaMatch_siteSR](https://github.com/AquaSat/AquaMatch_siteSR): This repository contains code that collates locations for acquisition of remote sensing data, and obtains, collates, and applies quality control filters on the resulting data.

[AquaMatch_lakeSR](https://github.com/AquaSat/AquaMatch_lakeSR): This repository contains code that calculates a centrally-located point within NHD waterbody features for remote sensing data acquisition, obtains, collates, and applies quality control filters on the resulting data. The code in this repository also calculates intermission handoff coefficients for Landsat Surface Reflectance data to allow for timeseries analysis across multiple sensors and atmospheric correction differences.

## Note

Landsat remote sensing images used in analyses courtesy of the United States Geological Survey. Any use of trade, firm, or product names is for descriptive purposes only and does not imply endorsement by the United States Government.

## Disclaimer

Unless otherwise stated, all data, metadata and related materials are considered to satisfy the quality standards relative to the purpose for which the data were collected. Although these data and associated metadata have been reviewed for accuracy and completeness and approved for release by the United States Geological Survey (USGS), no warranty expressed or implied is made regarding the display or utility of the data for other purposes, nor on all computer systems, nor shall the act of distribution constitute any such warranty.
