---
editor_options: 
  markdown: 
    wrap: 80
bibliography: references.bib
---
Note: the output of this is too large for GH without LFS. Leaving for now as code, 
but not rendering. 
```{r chunk-opts}
knitr::opts_chunk$set(echo = F, message = F, warning = F, error = FALSE)
```

```{r}
library(tidyverse)
library(sf)
library(leaflet)
library(withr)
library(targets)

with_dir("..", {
  tar_load(combined_poi_points)
})

```

# Locations Map

Figure \@ref(fig:map-of-poi) shows
the calculated POIs used for satellite data acquisition in **lakeSR**.

```{r map-of-poi, fig.cap="Map of POI's included in lakeSR. Note that the polygons shown on the map are not the NHD polygons and may reflect different geometries than those used to define the POI. The NHD Permanent ID is provided when no `GNIS_Name` was provided in the upstream NHD files."}
points <- combined_poi_points %>% 
  mutate(name = if_else(is.na(GNIS_Name),
                        paste0('NHD ID: ', Permanent_Identifier, '; ',
                               'FCode: ', FCODE),
                        paste0('GNIS Name: ', GNIS_Name, '; ',
                               'NHD ID: ', Permanent_Identifier, '; ',
                               'FCode: ', FCODE))) %>% 
  st_as_sf(., 
           coords = c("poi_Longitude", "poi_Latitude"), 
           crs = "EPSG:4326")

leaflet(data = points) %>% 
  addTiles(urlTemplate = "'https://{s}.basemaps.cartocdn.com/light_nolabels/{z}/{x}/{y}{r}.png") %>% 
  addMarkers(label = ~name,
             popup = ~name,
             clusterOptions = markerClusterOptions())
```